from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ReferenceItem(BaseModel):
    snippet: str = Field(..., description="The context snippet retrieved.")
    answer_source: str = Field(..., description="The expert answer source.")

class ChatResponse(BaseModel):
    response: str = Field(..., description="The final response in the user's original language.")
    language: str = Field(..., description="The language detected from the user's input.")
    intent: str = Field(..., description="The classified intent of the user's query.")
    emotion: str = Field(..., description="The classified emotion of the user's query.")
    emotion_confidence: float = Field(..., description="The confidence score of the emotion classification.")
    english_query: str = Field(..., description="The intermediate English translation of the user's query.")
    english_response: str = Field(..., description="The intermediate English response generated by the LLM.")
    references: Optional[List[Dict[str, Any]]] = Field(default=[], description="Source references used in case of RAG.")
